### ISSUE TITLE
NuGet package?

### ISSUE THREAD

**Issue by danielchalmers** [MisinformedDNA/YellowCounter.FileSystemState#1]
loving this project! great alternative to FileSystemWatcher.  
do you have any plans to release a nuget package until it's potentially moved to corefxlab?  
thanks!

**Comment by MisinformedDNA** [comment]
Sorry. I totally did this the next day and then forgot to update here. Here it is: [YellowCounter.FileSystemState](https://www.nuget.org/packages/YellowCounter.FileSystemState/)
